# Generated by Django 5.0.7 on 2024-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_profile_ppic'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostore',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
